# Generated by Django 2.2.5 on 2019-09-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='male', max_length=255)),
                ('title', models.CharField(default='mr', max_length=255)),
                ('fname', models.CharField(default='John', max_length=255)),
                ('lname', models.CharField(default='Doe', max_length=255)),
                ('phone', models.CharField(default='+4411 2358 13 21', max_length=255)),
                ('email', models.EmailField(default='email@example.com', max_length=255)),
            ],
            options={
                'verbose_name': 'API user',
                'verbose_name_plural': 'API users',
                'db_table': 'random_user',
            },
        ),
    ]
